name: dead_end_bunker
max_steps: 220
scan_radius: 1
grid:
  - "###############"
  - "#S....#.......#"
  - "#.###.#.#####.#"
  - "#...#.#...C...#"
  - "###.#.###.###.#"
  - "#...#.....#...#"
  - "#.#######.#.###"
  - "#C......#.#...#"
  - "#######.#.###.#"
  - "#.......#...C.#"
  - "###############"
