<?xml version="1.0"?>
<package format="3">
  <name>world_explorer</name>
  <version>0.1.0</version>
  <description>World explorer nodes that consume underground_world ROS interfaces.</description>

  <maintainer email="robotics@example.com">robot_dreams</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>underground_world</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
